singleServerConfig:
  idleConnectionTimeout: 30000
  connectTimeout: 30000
  timeout: 30000
  retryAttempts: 3
  retryInterval: 1500
  password: "demo"
  subscriptionsPerConnection: 5
  clientName: "Demo"
  address: "redis@example.com:8080"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 10
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 64
#codec: !org.redisson.codec.JsonJacksonCodec {}